---
### group_vars/DC1_SPINES.yml

type: spine

spine:
  defaults:
    platform: cEOSLab 
    loopback_ipv4_pool: 198.18.251.0/24 
    bgp_as: 4201010001

  nodes: 
    - name: dc1-sp1
      id: 1 
      mgmt_ip: 198.18.1.1/24
      downlink_pools:
        - ipv4_pool: 198.19.11.0/24
        - downlink_interfaces: [Ethernet1-12]

    - name: dc1-sp2
      id: 2
      mgmt_ip: 198.18.1.2/24
      downlink_pools:
        - ipv4_pool: 198.19.12.0/24
        - downlink_interfaces: [Ethernet1-12]

    - name: dc1-sp3
      id: 3
      mgmt_ip: 198.18.1.3/24
      downlink_pools:
        - ipv4_pool: 198.19.13.0/24
        - downlink_interfaces: [Ethernet1-12]
