---
### group_vars/DC2_SPINES.yml

type: spine

spine:
  defaults:
    platform: cEOSLab 
    loopback_ipv4_pool: 198.18.252.0/24 
    bgp_as: 4202020001

  nodes: 
    - name: dc2-sp1
      id: 1 
      mgmt_ip: 198.18.2.1/24

    - name: dc2-sp2
      id: 2
      mgmt_ip: 198.18.2.2/24


    - name: dc2-sp3
      id: 3
      mgmt_ip: 198.18.2.3/24
