---
### group_vars/NETWORK_SERVICES.yml

tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: TENANT1
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 100000
    vrfs:
      # VRF definitions inside the tenant.
      - name: ALPHA
        # VRF VNI definition.
        vrf_vni: 500001
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 501
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 198.19.51.0/24
        svis:
          # SVI definitions.
          - id: 1101
            # SVI Description
            name: ALPHA_VL1101
            enabled: true
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 198.19.101.255/24
          - id: 1102
            name: ALPHA_VL1102
            enabled: true
            ip_address_virtual: 198.19.102.255/24
      - name: BRAVO
        vrf_vni: 502
        vtep_diagnostic:
          loopback: 502
          loopback_ip_range: 10.198.19.52.0/24
        svis:
          - id: 1201
            name: BRAVO_VL1201
            enabled: true
            ip_address_virtual: 198.19.201.255/24
          - id: 1202
            name: BRAVO_VL1202
            enabled: true
            ip_address_virtual: 198.19.202.254/24

    l2vlans:
      # These are pure L2 vlans. They do not have a SVI defined in the l3leafs and they will be bridged inside the VXLAN fabric
      - id: 2501
        name: L2ONLY_VL2501
      - id: 2502
        name: L2ONLY_VL2502
